// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleProject.Data.Entity;

#nullable disable

namespace VehicleProject.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VehicleProject.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleProject.Models.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "RED"
                        },
                        new
                        {
                            Id = 2,
                            Color = "BLUE"
                        },
                        new
                        {
                            Id = 3,
                            Color = "BLACK"
                        },
                        new
                        {
                            Id = 4,
                            Color = "WHITE"
                        });
                });

            modelBuilder.Entity("VehicleProject.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "RED"
                        },
                        new
                        {
                            Id = 2,
                            Color = "BLUE"
                        },
                        new
                        {
                            Id = 3,
                            Color = "BLACK"
                        },
                        new
                        {
                            Id = 4,
                            Color = "WHITE"
                        });
                });

            modelBuilder.Entity("VehicleProject.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeadlightStatus")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "RED",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Color = "BLUE",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Color = "BLACK",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Color = "WHITE",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "RED",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Color = "BLUE",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 7,
                            Color = "BLACK",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        },
                        new
                        {
                            Id = 8,
                            Color = "WHITE",
                            HeadlightStatus = false,
                            NumberOfWheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
